### ISSUE TITLE
Undefined typeError

### ISSUE THREAD

**Issue by trexgerratt** [ArduPilot/WebTools#130]
I'm getting the following error with my logs from Arducopter 4.2

![image](https://github.com/ArduPilot/WebTools/assets/36173078/5b6fcc74-a996-4b96-814e-3ef2aacd878f)

Not sure if it's an issue or just from using an older firmware version, but I was able to mitigate this issue by modifying the source (using F12 in chrome) and putting the following lines in a try/catch:
`inst[instance].freq = all[i].freq`
`inst[instance].time_ms = all[i].time`
in the catch I would simply continue the loop.

I noticed that every 4th iteration of the loop would throw this error. Any ideas what is causing this?

See attached log.
[log.zip](https://github.com/ArduPilot/WebTools/files/14340042/log.zip)

**Comment by IamPete1** [comment]
Two fixes for this log. Should be live in half a hour or so, you will have to hard-reload the page. Thanks for the report!

**Comment by trexgerratt** [comment]
Beautiful. Thanks for the quick resolution!
