### ISSUE TITLE
Parameter transfer/copy tool

### ISSUE THREAD

**Issue by ronsand** [ArduPilot/WebTools#153]
A nice addition the the ArduPilot Web Tools would be a tool for selecting parameters and groups of parameters when copying/transferring settings from one FC to another. There should also be a selection to keep or discard calibration type parameters (compass, gyro etc).

In any case keep up the good work. I really like the tools and I'm using them more and more :)

**Comment by IamPete1** [comment]
Checkout the "Minimal Configuration" section in [Hardware Report](https://firmware.ardupilot.org/Tools/WebTools/HardwareReport/):

![image](https://github.com/ArduPilot/WebTools/assets/33176108/694a5473-6530-485c-a912-73a20fef3ea1)

**Comment by ronsand** [comment]
There you have it :) I missed that functionality when I looked at that tool.
Thanks 
Regards Ronny

**Comment by ronsand** [comment]
One thing I see is that you will have to use a log file (.bin) to get the "minimal configuration" to show up. That means you have to make a new flight, or enable "logging disarmed", in case you make changes after the flight and want to use that as a basis for copy.
Not a big deal, but is it be possible to get the "minimal configuration" also from the .param file (it is not as of now).

Thanks again
Regards Ronny

**Comment by IamPete1** [comment]
That should have worked already. It turns out we broke it for a bit.

This fixes the bug:
https://github.com/ArduPilot/WebTools/pull/155

This fixes the reason we did not notice the bug:
https://github.com/ArduPilot/WebTools/pull/154

Should be live in 30 mins or so, you will have to hard reload the page.

**Comment by ronsand** [comment]
That is what i call service. Excellent work :)
