### ISSUE TITLE
The "Position offsets" 3D graph does not work in Firefox browser

### ISSUE THREAD

**Issue by xgsa** [ArduPilot/WebTools#172]
The "Position offsets" 3D graph does not show anything in Firefox, whereas the position of the GPS module is set (note also the the axes are also not signed):
![Screenshot_20240710_132045](https://github.com/ArduPilot/WebTools/assets/875362/243d54bf-cf55-4dec-9d78-f6bfe1c03a31)

The same log in Chromium browser looks good:
![Screenshot_20240710_132058](https://github.com/ArduPilot/WebTools/assets/875362/a367268e-48c7-4833-b200-a315973dc698)

Firefox version is 127.0.2 (64-bit).
Platform: Ubuntu 22.04.4 LTS.

P.S. Thank you very much for the bunch of useful tools!

**Comment by IamPete1** [comment]
Thanks for the report. 

I think this is the same issue as https://github.com/plotly/plotly.js/issues/4943. I was able to reproduce by setting `privacy.resistFingerprinting` `true` in firefox `about:config`. 

Adding `https://firmware.ardupilot.org/` to `privacy.resistFingerprinting.exemptedDomains` resolved it for me (or just turning off resist finger printing of course).

![image](https://github.com/ArduPilot/WebTools/assets/33176108/933b1c8a-a67a-4f92-84fb-8fb73de2b158)
 
Unfortunately I don't think there is anything we can do to fix it from our side.

**Comment by xgsa** [comment]
Thank you for the advice, but unfortunately it didn't help (I already had privacy.resistFingerprinting set to false).
I agree that it's rather a bug of plotly, still possibly you could upgrade its version if it's not the latest yet.
