### ISSUE TITLE
Webtools on local server

### ISSUE THREAD

**Issue by ducbruno** [ArduPilot/WebTools#179]
Hello, 

I want to use the webtools on local server. I made the steps as mentioned in the readme file of the repo, and when loading a bin file in Filter review for example, I got an error message states that the Hanning function is not declared in java script file.

Thanks in advance

**Comment by IamPete1** [comment]
It sounds like you may not be hosting the tools correctly. Host with:
```
python -m http.server --bind 127.0.0.1
```
Then use the page at ```http://127.0.0.1:8000/```

Is that what you have done?

**Comment by IamPete1** [comment]
@ducbruno Any update? I'm going to close for now, please re-open if this is still a issue.
