### ISSUE TITLE
Loading large (~170MB) log in Chrome: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by WARGRaph** [ArduPilot/WebTools#195]
Hi, 

my Copter Autotune gave back bad results, so I wanted to verify my filters from the log of that flight, which is ~170MB big. 
Trying to load in in Chrome gives me the following errors: 
![grafik](https://github.com/user-attachments/assets/66b223f7-1d33-4be3-a52d-ff9ddb843e64)
![grafik](https://github.com/user-attachments/assets/83761db7-aa11-4b2f-ab48-7cdae7181e04)

Firefox takes a long time, but succeeds eventually. 
Clearing the cache or reloading the page or restarting the browser doesn't help.

**Comment by IamPete1** [comment]
Unfortunately this is just a limitation of chrome, it has a per tab memory limit. I have done my best to minimise the memory usage, but sometimes the only way is just to use another browser. 

If you post the log I can try it here and see if its using more memory than it should, but I think its more or less expected.

**Comment by WARGRaph** [comment]
I would prefer not to post it publicly, but I can send it to you if you sanitize it or delete it after checking it.

**Comment by IamPete1** [comment]
> I would prefer not to post it publicly, but I can send it to you if you sanitize it or delete it after checking it.

Sure, feel free to send it privately.

**Comment by IamPete1** [comment]
https://github.com/ArduPilot/WebTools/pull/197 fixes the call stack issue, but I still can't load the log on chrome. It does get a bit further and then the whole page crashes.

**Comment by IamPete1** [comment]
Closed by #197
