### ISSUE TITLE
ThrustExpo: scrolling causes unwanted updates

### ISSUE THREAD

**Issue by yuri-rage** [ArduPilot/WebTools#212]
Scrolling the page with a mouse wheel (or dragging with a touch gesture) triggers an update function that recalculates the optimal expo value rather than keeping a user edited value.

Guessing a prevent default method could be applied to the offending element's scroll event (probably within the Tabulator element).

**Comment by IamPete1** [comment]
Fixed by https://github.com/ArduPilot/WebTools/pull/213
