### ISSUE TITLE
Suggest an "un-zoom" feature, and explanation of FFT versus RPM notch analysis

### ISSUE THREAD

**Issue by joe-stroup** [ArduPilot/WebTools#218]
I've just been introduced to this tool - and along with it the companion PID review tool.  I'm looking forward to learning how to use these tools to my best advantage.

After a first look at these tools I have two suggestions:

1) I couldn't find a way to "un-zoom" back to the whole data set after zooming in on a particular area.  If it exists, I'm sorry that I missed it.  But the only way I could go back to the whole dataset was to reload the BIN file.

2) The very nice YouTube video that explains how to use the Filter Review Tool appears to focus on FFT notch filters.  I'm using bd-shot and RPM telemetry for my filter.  The video shows some "width" of the notches - I assume because of the FFT calculations.  In my case, the notch is shown as a single line.  If I have this right - it would be nice to better understand what, if any difference, this tool can help analyze between these two filter types.  In particular, I'm wondering how to best use the tool to set the proper bandwidth for the notch filter.

Thanks for this great work!

**Comment by IamPete1** [comment]
> 1. I couldn't find a way to "un-zoom" back to the whole data set after zooming in on a particular area.  If it exists, I'm sorry that I missed it.  But the only way I could go back to the whole dataset was to reload the BIN file.

You can double click on the plot to reset, or the home or auto scale in the top right. 
![image](https://github.com/user-attachments/assets/6535cb92-f48f-4a10-b546-1c04b2cfcf4f)

> 2\. The very nice YouTube video that explains how to use the Filter Review Tool appears to focus on FFT notch filters.  I'm using bd-shot and RPM telemetry for my filter.  The video shows some "width" of the notches - I assume because of the FFT calculations.  In my case, the notch is shown as a single line.  If I have this right - it would be nice to better understand what, if any difference, this tool can help analyze between these two filter types.  In particular, I'm wondering how to best use the tool to set the proper bandwidth for the notch filter.

No FFT filters in demo, throttle, ESC and RPM based. If you have a single line in the plot it means your configuration is not letting the filters track.

**Comment by joe-stroup** [comment]
Thank you for the clarification - I appreciate it.  And very helpful!

I don't understand "not letting the filters track."  How is this controlled?  Is it important?

I've gotten excellent help from the discuss forum on using Filter Review Tool.  It's been suggested that I use the "multi-source" harmonic notch option parameter.  Will this accomplish letting the filters track?

BTW - the Filter Review Tool isn't mentioned in the ArduPilot wiki except at the bottom of a page on filters.  Comments on the forum suggest that the original FFT analysis tool is not obsolete and everyone should be using the newer Filter Review Tool.  More people might use this tool if it were more prominent in the wiki.  I'm pretty active on the ardupilot.org group on facebook.  I'll make a post there to remind people of both the Filter Review Tool and the PID Review tool.  I've never seen either tool mentioned in that group.

Thank you for taking the time to respond.

**Comment by joe-stroup** [comment]
Here's the log that posted in my comment thread where I learned about the Filter Review Tool.  It shows the "line" where the notch exists.  https://drive.google.com/file/d/1muKhGId1SBFoZkpaoPWsyc8YN21r5_7z/view?usp=drive_link

**Comment by IamPete1** [comment]
> Here's the log that posted in my comment thread where I learned about the Filter Review Tool. It shows the "line" where the notch exists. https://drive.google.com/file/d/1muKhGId1SBFoZkpaoPWsyc8YN21r5_7z/view?usp=drive_link

Set `INS_HNTCH_REF` to 1.0. Zero is turning off the tracking. 



> BTW - the Filter Review Tool isn't mentioned in the ArduPilot wiki except at the bottom of a page on filters. Comments on the forum suggest that the original FFT analysis tool is now obsolete and everyone should be using the newer Filter Review Tool. More people might use this tool if it were more prominent in the wiki. I'm pretty active on the ardupilot.org group on facebook. I'll make a post there to remind people of both the Filter Review Tool and the PID Review tool. I've never seen either tool mentioned in that group.

Your quite right, it should be more prominent on the wiki. Many of the devs at better at writing code than editing the wiki, so it tends to be forgotten. Any help keeping the wiki upto date would be much appreciated.
